# Generated by Django 2.1.1 on 2018-11-28 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('read_statistics', '0002_auto_20181118_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readdetail',
            options={'ordering': ['-view_time'], 'verbose_name': '阅读详情', 'verbose_name_plural': '阅读详情'},
        ),
        migrations.AddField(
            model_name='readdetail',
            name='ip_address',
            field=models.CharField(default='0.0.0.0', max_length=15),
        ),
        migrations.AddField(
            model_name='readdetail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='readdetail',
            name='view_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
