# Generated by Django 2.1.1 on 2018-11-24 03:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0002_auto_20181118_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='readdetail',
            name='view_num',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
