# Generated by Django 2.1.1 on 2018-11-24 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('read_statistics', '0003_readdetail_view_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readdetail',
            old_name='view_num',
            new_name='view_time',
        ),
        migrations.AddField(
            model_name='readdetail',
            name='ip_address',
            field=models.CharField(default='0.0.0.0', max_length=15),
        ),
        migrations.AddField(
            model_name='readdetail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
