# Generated by Django 2.1.1 on 2018-10-27 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='dht11value',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='ds18b20value',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='lightvalue',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='mq2value',
            field=models.CharField(max_length=10),
        ),
    ]
