# Generated by Django 2.1.1 on 2018-12-14 12:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181118_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='no'),
            preserve_default=False,
        ),
    ]
