# Generated by Django 2.1.1 on 2018-12-15 12:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='img'),
            preserve_default=False,
        ),
    ]
