# Generated by Django 2.1.1 on 2018-11-28 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
            },
        ),
        migrations.RenameModel(
            old_name='Info',
            new_name='About',
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': '关于', 'verbose_name_plural': '关于'},
        ),
    ]
