# Generated by Django 2.1.1 on 2018-11-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20181128_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='text',
            new_name='content',
        ),
        migrations.AddField(
            model_name='notice',
            name='title',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
