# Generated by Django 2.1.1 on 2018-11-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20181128_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='title',
        ),
        migrations.AddField(
            model_name='notice',
            name='send_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
