# Generated by Django 2.1.1 on 2018-11-28 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20181128_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='send_time',
            new_name='creat_time',
        ),
        migrations.RemoveField(
            model_name='about',
            name='send_time',
        ),
        migrations.RemoveField(
            model_name='about',
            name='user',
        ),
    ]
