# Generated by Django 2.1.1 on 2018-10-27 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='电话')),
            ],
        ),
        migrations.RemoveField(
            model_name='phone',
            name='user',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
