# Generated by Django 2.1.1 on 2018-11-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20181027_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone_profile',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
