# Generated by Django 2.1.1 on 2018-11-16 10:37

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='comment_time',
            new_name='send_time',
        ),
        migrations.AlterField(
            model_name='info',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
