# Generated by Django 2.1.1 on 2018-11-18 06:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20181116_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=django.utils.timezone.now, verbose_name='日期')),
                ('count', models.IntegerField(default=0, verbose_name='网站访问次数')),
            ],
            options={
                'verbose_name': '网站日访问量',
                'verbose_name_plural': '网站日访问量',
            },
        ),
        migrations.CreateModel(
            name='Userip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30, verbose_name='IP地址')),
                ('count', models.IntegerField(default=0, verbose_name='访问次数')),
            ],
            options={
                'verbose_name': '访问ip统计',
                'verbose_name_plural': '访问ip统计',
            },
        ),
        migrations.CreateModel(
            name='VisitNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(default='lkqblog.cn', max_length=20, verbose_name='站名')),
                ('count', models.IntegerField(default=0, verbose_name='网站总访次数')),
            ],
            options={
                'verbose_name': '网站总访问数',
                'verbose_name_plural': '网站总访问数',
            },
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': '公告', 'verbose_name_plural': '公告'},
        ),
        migrations.AlterModelOptions(
            name='phone_profile',
            options={'verbose_name': '电话', 'verbose_name_plural': '电话'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '昵称', 'verbose_name_plural': '昵称'},
        ),
    ]
