# Generated by Django 2.1.1 on 2018-11-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_visitnumber_site'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daynumber',
            options={'verbose_name': '网站日访问量', 'verbose_name_plural': '网站日访问量'},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': '公告', 'verbose_name_plural': '公告'},
        ),
        migrations.AlterModelOptions(
            name='phone_profile',
            options={'verbose_name': '电话', 'verbose_name_plural': '电话'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '昵称', 'verbose_name_plural': '昵称'},
        ),
        migrations.AlterModelOptions(
            name='userip',
            options={'verbose_name': '访问ip统计', 'verbose_name_plural': '访问ip统计'},
        ),
        migrations.AlterModelOptions(
            name='visitnumber',
            options={'verbose_name': '网站总访问数', 'verbose_name_plural': '网站总访问数'},
        ),
        migrations.AlterField(
            model_name='visitnumber',
            name='count',
            field=models.IntegerField(default=0, verbose_name='网站总访次数'),
        ),
    ]
